version: "3.9"

services:
  web-blue:
    image: html-ci-demo:${TAG}
    container_name: web-blue
    ports:
      - "8085:80"
    restart: unless-stopped

  web-green:
    image: html-ci-demo:${TAG}
    container_name: web-green
    ports:
      - "8086:80"
    restart: unless-stopped
